namespace SharpMeasures.Generators.Scalars.Pipelines.DimensionalEquivalence;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.Quantities.Utility;
using SharpMeasures.Generators.Scalars.Refinement;
using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Text;
using System.Linq;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, DataModel data)
    {
        if (data.DimensionalEquivalences.Any() is false)
        {
            return;
        }

        string source = Composer.Compose(context, data);

        context.AddSource($"{data.Scalar.Name}_DimensionalEquivalence.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private class Composer
    {
        public static string Compose(SourceProductionContext context, DataModel data)
        {
            Composer composer = new(context, data);
            composer.Compose();
            return composer.Retrieve();
        }

        private SourceProductionContext Context { get; }
        private StringBuilder Builder { get; } = new();
        private UsingsCollector UsingsCollector { get; }

        private DataModel Data { get; }

        private Composer(SourceProductionContext context, DataModel data)
        {
            Context = context;
            Data = data;

            UsingsCollector = UsingsCollector.Delayed(Builder, data.Scalar.Namespace);
        }

        private void Compose()
        {
            StaticBuilding.AppendAutoGeneratedHeader(Builder);
            StaticBuilding.AppendNullableDirective(Builder);

            UsingsCollector.MarkInsertionPoint();

            NamespaceBuilding.AppendNamespace(Builder, Data.Scalar.Namespace);

            Builder.Append(Data.Scalar.ComposeDeclaration());

            BlockBuilding.AppendBlock(Builder, ComposeTypeBlock, originalIndentationLevel: 0);

            UsingsCollector.InsertUsings();
        }

        private string Retrieve()
        {
            return Builder.ToString();
        }

        private void ComposeTypeBlock(Indentation indentation)
        {
            foreach (RefinedDimensionalEquivalenceDefinition definition in Data.DimensionalEquivalences)
            {
                foreach (ScalarInterface scalar in definition.Quantities)
                {
                    ComposeInstanceConversion(scalar, indentation);
                    Builder.AppendLine();
                }
            }

            foreach (RefinedDimensionalEquivalenceDefinition definition in Data.DimensionalEquivalences)
            {
                if (definition.CastOperatorBehaviour is ConversionOperationBehaviour.None)
                {
                    continue;
                }

                Action<ScalarInterface, Indentation> composer = definition.CastOperatorBehaviour switch
                {
                    ConversionOperationBehaviour.Explicit => ComposeExplicitOperatorConversion,
                    ConversionOperationBehaviour.Implicit => ComposeImplicitOperatorConversion,
                    _ => throw new NotSupportedException("Invalid cast operation")
                };

                foreach (ScalarInterface scalar in definition.Quantities)
                {
                    composer(scalar, indentation);
                    Builder.AppendLine();
                }
            }

            SourceBuildingUtility.RemoveOneNewLine(Builder);
        }

        private void ComposeInstanceConversion(ScalarInterface scalar, Indentation indentation)
        {
            UsingsCollector.AddUsing(scalar.ScalarType.Namespace);

            AppendDocumentation(indentation, ScalarDocumentationTags.DimensionallyEquivalentTo(scalar.ScalarType.Name));
            Builder.AppendLine($"{indentation}public {scalar.ScalarType.Name} As{scalar.ScalarType.Name} => new(Magnitude);");
        }

        private void ComposeExplicitOperatorConversion(ScalarInterface scalar, Indentation indentation)
            => ComposeOperatorConversion(scalar, indentation, "explicit");

        private void ComposeImplicitOperatorConversion(ScalarInterface scalar, Indentation indentation)
            => ComposeOperatorConversion(scalar, indentation, "implicit");

        private void ComposeOperatorConversion(ScalarInterface scalar, Indentation indentation, string behaviour)
        {
            AppendDocumentation(indentation, ScalarDocumentationTags.Operators.DimensionallyEquivalentTo(scalar.ScalarType.Name));
            Builder.AppendLine($"{indentation}public static {behaviour} operator {scalar.ScalarType.Name}({Data.Scalar.Name} x) => new(x.Magnitude);");
        }

        private void AppendDocumentation(Indentation indentation, string tag)
        {
            DocumentationBuilding.AppendDocumentation(Context, Builder, Data.Documentation, indentation, tag);
        }
    }
}
