namespace SharpMeasures.Generators.Vectors.Pipelines.Misc;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Text;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, DataModel data)
    {
        string source = Composer.Compose(context, data);

        context.AddSource($"{data.Vector.Name}_{data.Dimension}_Misc.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private class Composer
    {
        public static string Compose(SourceProductionContext context, DataModel data)
        {
            Composer composer = new(context, data);
            composer.Compose();
            return composer.Retrieve();
        }

        private SourceProductionContext Context { get; }
        private StringBuilder Builder { get; } = new();

        private DataModel Data { get; }
        private UsingsCollector UsingsCollector { get; }

        private VectorTexts ComponentTypeTupleElements_UpperCased { get; }
        private VectorTexts ComponentTypeTupleElements_LowerCased { get; }
        private VectorTexts NewComponentType_LowerCased { get; }

        private Composer(SourceProductionContext context, DataModel data)
        {
            Context = context;
            Data = data;

            ComponentTypeTupleElements_UpperCased = VectorTexts.CommaSeparatedElements_UpperCased(Data.Scalar is null ? "Scalar" : Data.Scalar.Value.Name);
            ComponentTypeTupleElements_LowerCased = VectorTexts.CommaSeparatedElements_LowerCased(Data.Scalar is null ? "Scalar" : Data.Scalar.Value.Name);
            NewComponentType_LowerCased = Texts.NewComponentType_LowerCased(Data.Scalar is null ? "Scalar" : Data.Scalar.Value.Name);

            UsingsCollector = UsingsCollector.Delayed(Builder, Data.Vector.Namespace);
            UsingsCollector.AddUsings("SharpMeasures", "SharpMeasures.Maths", Data.Unit.Namespace);

            if (Data.Scalar is not null)
            {
                UsingsCollector.AddUsing(Data.Scalar.Value.Namespace);
            }

            if (Data.Dimension is 3)
            {
                UsingsCollector.AddUsing("System.Numerics");
            }
        }

        private void Compose()
        {
            StaticBuilding.AppendAutoGeneratedHeader(Builder);
            StaticBuilding.AppendNullableDirective(Builder);

            NamespaceBuilding.AppendNamespace(Builder, Data.Vector.Namespace);

            UsingsCollector.MarkInsertionPoint();

            AppendDocumentation(new Indentation(0), VectorDocumentationTags.VectorHeader);
            Builder.AppendLine(Data.Vector.ComposeDeclaration());

            InterfaceBuilding.AppendInterfaceImplementation(Builder, new string[]
            {
                $"IVector{Data.Dimension}"
            });

            BlockBuilding.AppendBlock(Builder, ComposeTypeBlock, originalIndentationLevel: 0);

            UsingsCollector.InsertUsings();
        }

        private string Retrieve()
        {
            return Builder.ToString();
        }

        private void ComposeTypeBlock(Indentation indentation)
        {
            AppendDocumentation(indentation, VectorDocumentationTags.Zero);
            Builder.AppendLine($"{indentation}public static {Data.Vector.Name} Zero {{ get; }} = new({Texts.Zeros.GetText(Data.Dimension)});");

            Builder.AppendLine();

            ComposeComponents(indentation);

            Builder.AppendLine();

            ComposeConstructors(indentation);

            Builder.AppendLine();

            ComposeMagnitude(indentation);

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Normalize);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name} Normalize() => this / {(Data.Scalar is null ? "Magnitude()" : "Magnitude().Magnitude")};");

            if (Data.Dimension is 3)
            {
                AppendDocumentation(indentation, VectorDocumentationTags.Transform);
                Builder.AppendLine($"{indentation}public {Data.Vector.Name} Transform(Matrix4x4 transform) => VectorMaths.Transform(this, transform);");
            }

            AppendDocumentation(indentation, VectorDocumentationTags.Dot_Vector);
            Builder.Append($"{indentation}public {Data.}")
        }

        private void ComposeComponents(Indentation indentation)
        {
            if (Data.Scalar is null)
            {
                ComposeComponentsAsScalars(indentation);
            }
            else
            {
                ComposeComponentsAsTypes(indentation, Data.Scalar.Value);
            }
        }

        private void ComposeConstructors(Indentation indentation)
        {
            if (Data.Scalar is null)
            {
                ComposeConstructorsToScalars(indentation);
            }
            else
            {
                ComposeConstructorsToTypes(indentation);
            }

            Builder.AppendLine();
            ComposeCommonConstructors(indentation);
        }

        private void ComposeMagnitude(Indentation indentation)
        {
            if (Data.Scalar is null)
            {
                AppendDocumentation(indentation, VectorDocumentationTags.Magnitude);
                Builder.AppendLine($"{indentation}public Scalar Magnitude() => VectorMaths.Dot(this, this).SquareRoot();");
            }
            else
            {
                AppendDocumentation(indentation, VectorDocumentationTags.Magnitude);
                Builder.AppendLine($"{indentation}public {Data.Scalar.Value.Name} Magnitude() => new(VectorMaths.Dot(this, this).SquareRoot());");

                Builder.AppendLine($"{indentation}/// <inheritdoc/>");
                Builder.AppendLine($"{indentation}Scalar IVector{Data.Dimension}.Magnitude() => VectorMaths.Dot(this, this).SquareRoot());");
            }

            Builder.AppendLine();

            if (Data.SquaredScalar is null)
            {
                AppendDocumentation(indentation, VectorDocumentationTags.SquaredMagnitude);
                Builder.AppendLine($"{indentation}public Scalar SquaredMagnitude() => VectorMaths.Dot(this, this);");
            }
            else
            {
                AppendDocumentation(indentation, VectorDocumentationTags.SquaredMagnitude);
                Builder.AppendLine($"{indentation}public {Data.SquaredScalar} SquaredMagnitude() => new(VectorMaths.Dot(this, this));");

                Builder.AppendLine($"{indentation}/// <inheritdoc/>");
                Builder.AppendLine($"{indentation}Scalar IVector{Data.Dimension}.SquaredMagnitude() => VectorMaths.Dot(this, this);");
            }
        }

        private void ComposeComponentsAsScalars(Indentation indentation)
        {
            for (int i = 0; i < Data.Dimension; i++)
            {
                AppendDocumentation(indentation, VectorDocumentationTags.Component(i, Data.Dimension));
                Builder.AppendLine($"{indentation}public Scalar {VectorTexts.GetUpperCasedComponentName(i, Data.Dimension)} {{ get; }}");
            }

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Components);
            Builder.AppendLine($"{indentation}public Vector{Data.Dimension} Components => new({VectorTexts.CommaSeparatedNames_UpperCased.GetText(Data.Dimension)});");
        }

        private void ComposeComponentsAsTypes(Indentation indentation, NamedType scalar)
        {
            for (int i = 0; i < Data.Dimension; i++)
            {
                AppendDocumentation(indentation, VectorDocumentationTags.Component(i, Data.Dimension));
                Builder.AppendLine($"{indentation}public {scalar.Name} {VectorTexts.GetUpperCasedComponentName(i, Data.Dimension)} {{ get; }}");
            }

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Components);
            Builder.AppendLine($"{indentation}public Vector{Data.Dimension} Components => new({VectorTexts.CommaSeparatedNames_UpperCased.GetText(Data.Dimension)});");

            Builder.AppendLine();

            for (int i = 0; i < Data.Dimension; i++)
            {
                Builder.AppendLine($"{indentation}/// <inheritdoc/>");
                Builder.AppendLine($"{indentation}Scalar IVector{Data.Dimension}.{VectorTexts.GetUpperCasedComponentName(i, Data.Dimension)}Magnitude => {VectorTexts.GetUpperCasedComponentName(i, Data.Dimension)}.Magnitude;");
            }
        }

        private void ComposeConstructorsToScalars(Indentation indentation)
        {
            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Scalars);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}({Texts.ScalarTupleElements_LowerCased.GetText(Data.Dimension)})");
            BlockBuilding.AppendBlock(Builder, ComposeConstructorBlock, indentation);
        }

        private void ComposeConstructorsToTypes(Indentation indentation)
        {
            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Components);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}({ComponentTypeTupleElements_LowerCased.GetText(Data.Dimension)})");
            BlockBuilding.AppendBlock(Builder, ComposeConstructorBlock, indentation);

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_ComponentTuple);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(({ComponentTypeTupleElements_UpperCased.GetText(Data.Dimension)}) components)");
            Builder.AppendLine($"{indentation.Increased}: this({VectorTexts.ComponentTupleAccess_UpperCased.GetText(Data.Dimension)}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Scalars);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}({Texts.ScalarTupleElements_LowerCased.GetText(Data.Dimension)})");
            Builder.AppendLine($"{indentation.Increased}: this({NewComponentType_LowerCased.GetText(Data.Dimension)}) {{ }}");
        }

        private void ComposeConstructorBlock(Indentation indentation)
        {
            for (int i = 0; i < Data.Dimension; i++)
            {
                Builder.AppendLine($"{indentation}{VectorTexts.GetUpperCasedComponentName(i, Data.Dimension)} = {VectorTexts.GetLowerCasedComponentName(i, Data.Dimension)};");
            }
        }

        private void ComposeCommonConstructors(Indentation indentation)
        {
            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_ScalarTuple);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(({Texts.ScalarTupleElements_UpperCased.GetText(Data.Dimension)}) components)");
            Builder.AppendLine($"{indentation.Increased}: this({VectorTexts.ComponentTupleAccess_UpperCased.GetText(Data.Dimension)}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Doubles);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}({Texts.DoubleTupleElements_LowerCased.GetText(Data.Dimension)})");
            Builder.AppendLine($"{indentation.Increased}: this({Texts.NewScalar_LowerCased.GetText(Data.Dimension)}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_DoubleTuple);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(({Texts.DoubleTupleElements_UpperCased.GetText(Data.Dimension)}) components)");
            Builder.AppendLine($"{indentation.Increased}: this({VectorTexts.ComponentTupleAccess_UpperCased.GetText(Data.Dimension)}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Vector);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(Vector{Data.Dimension}) components)");
            Builder.AppendLine($"{indentation.Increased}: this({VectorTexts.ComponentTupleAccess_UpperCased.GetText(Data.Dimension)}) {{ }}");

            Builder.AppendLine();

            string unitParameterName = SourceBuildingUtility.ToParameterName(Data.Unit.Name);

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Unit_ScalarTuple);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(({Texts.ScalarTupleElements_UpperCased.GetText(Data.Dimension)}) components, {Data.Unit.Name} {unitParameterName})");
            Builder.AppendLine($"{indentation.Increased}: this(components * {unitParameterName}.{Data.UnitQuantity.Name}.Magnitude) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Unit_Scalars);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}({Texts.ScalarTupleElements_LowerCased.GetText(Data.Dimension)}, {Data.Unit.Name} {unitParameterName})");
            Builder.AppendLine($"{indentation.Increased}: this(({VectorTexts.CommaSeparatedNames_LowerCased.GetText(Data.Dimension)}), {unitParameterName}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Unit_Doubles);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}({Texts.ScalarTupleElements_LowerCased.GetText(Data.Dimension)}, {Data.Unit.Name} {unitParameterName})");
            Builder.AppendLine($"{indentation.Increased}: this(({Texts.NewScalar_LowerCased.GetText(Data.Dimension)}), {unitParameterName}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Unit_DoubleTuple);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(({Texts.ScalarTupleElements_UpperCased.GetText(Data.Dimension)}) components, {Data.Unit.Name} {unitParameterName})");
            Builder.AppendLine($"{indentation.Increased}: this({VectorTexts.ComponentTupleAccess_UpperCased.GetText(Data.Dimension)}, {unitParameterName}) {{ }}");

            Builder.AppendLine();

            AppendDocumentation(indentation, VectorDocumentationTags.Constructor_Unit_Vector);
            Builder.AppendLine($"{indentation}public {Data.Vector.Name}(Vector{Data.Dimension} components, {Data.Unit.Name} {unitParameterName})");
            Builder.AppendLine($"{indentation.Increased}: this(({VectorTexts.ComponentTupleAccess_UpperCased.GetText(Data.Dimension)}), {unitParameterName}) {{ }}");
        }

        private void AppendDocumentation(Indentation indentation, string tag)
        {
            DocumentationBuilding.AppendDocumentation(Context, Builder, Data.Documentation, indentation, tag);
        }
    }

    private static class Texts
    {
        public static VectorTexts Zeros { get; } = new("0", ", ");
        public static VectorTexts ScalarTupleElements_UpperCased { get; } = VectorTexts.CommaSeparatedElements_UpperCased("Scalar");
        public static VectorTexts ScalarTupleElements_LowerCased { get; } = VectorTexts.CommaSeparatedElements_UpperCased("Scalar");
        public static VectorTexts DoubleTupleElements_UpperCased { get; } = VectorTexts.CommaSeparatedElements_UpperCased("Scalar");
        public static VectorTexts DoubleTupleElements_LowerCased { get; } = VectorTexts.CommaSeparatedElements_UpperCased("Scalar");

        public static VectorTexts NewComponentType_LowerCased(string componentType)
        {
            return new VectorTexts(newComponentType_LowerCasedComponent, ", ");

            string newComponentType_LowerCasedComponent(int componentIndex, int dimension)
            {
                return $"new {componentType}({VectorTexts.GetLowerCasedComponentName(componentIndex, dimension)})";
            }
        }

        public static VectorTexts NewScalar_LowerCased { get; } = new VectorTexts(NewScalar_LowerCasedComponent, ", ");

        private static string NewScalar_LowerCasedComponent(int componentIndex, int dimension)
        {
            return $"new Scalar({VectorTexts.GetLowerCasedComponentName(componentIndex, dimension)})";
        }
    }
}
