//HintName: UnitOfLength_Common.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Units <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

/// <summary>A unit of measurement, primarily describing <see cref="global::Length"/>.</summary>
public partial class UnitOfLength :
    global::System.IComparable<UnitOfLength>,
    global::System.IEquatable<UnitOfLength>
{
    /// <summary>The <see cref="global::Length"/> described by <see langword="this"/>.</summary>
    public global::Length Length { get; }

    /// <summary>Constructs a new <see cref="global::UnitOfLength"/>, describing <paremref name="length"/>.</summary>
    /// <param name="length">The <see cref="global::Length"/> described by the constructed <see cref="global::UnitOfLength"/>.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    private UnitOfLength(global::Length length)
    {
        global::System.ArgumentNullException.ThrowIfNull(length);

        Length = length;
    }

    /// <summary>Scales the <see cref="global::Length"/> described by <see langword="this"/> by <paramref name="scale"/> to derive a new <see cref="global::UnitOfLength"/>.</summary>
    /// <param name="scale">The described <see cref="global::Length"/> is scaled by this value.</param>
    public global::UnitOfLength ScaledBy(global::SharpMeasures.Scalar scale) => new(Length * scale);

    /// <summary>Prefixes the <see cref="global::Length"/> described by <see langword="this"/> with <paramref name="prefix"/> to derive a new <see cref="global::UnitOfLength"/>.</summary>
    /// <param name="prefix">The described <see cref="global::Length"/> is prefixed by this <see cref="global::SharpMeasures.IPrefix"/>.</param>
    /// <remarks>Repeated invokation will <i>stack</i> the prefixes, rather than <i>replace</i> the previously applied <see cref="global::SharpMeasures.IPrefix"/>.</remarks>
    /// <exception cref="global::System.ArgumentNullException"/>
    public global::UnitOfLength WithPrefix<TPrefix>(TPrefix prefix) where TPrefix : global::SharpMeasures.IPrefix
    {
        global::System.ArgumentNullException.ThrowIfNull(prefix);

        return new(Length * prefix.Factor);
    }

    ///<summary>Produces a description of <see langword="this"/> containing the type and the described <see cref="global::Length"/>.</summary>
    public override string ToString() => Length.ToString();

    /// <inheritdoc/>
    public virtual bool Equals(global::UnitOfLength? other) => other is not null && Length == other.Length;

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is global::UnitOfLength other && Equals(other);

    /// <summary>Indicates whether <paramref name="lhs"/> and <paramref name="rhs"/> represent equivalent <see cref="global::Length"/>.</summary>
    /// <param name="lhs">The left-hand side of the equality check.</param>
    /// <param name="rhs">The right-hand side of the equality check.</param>
    public static bool operator ==(global::UnitOfLength? lhs, global::UnitOfLength? rhs) => lhs?.Equals(rhs) ?? rhs is null;

    /// <summary>Indicates whether <paramref name="lhs"/> and <paramref name="rhs"/> represent inequivalent <see cref="global::Length"/>.</summary>
    /// <param name="lhs">The left-hand side of the inequality check.</param>
    /// <param name="rhs">The right-hand side of the inequality check.</param>
    public static bool operator !=(global::UnitOfLength? lhs, global::UnitOfLength? rhs) => (lhs == rhs) is false;

    /// <inheritdoc/>
    public override int GetHashCode() => Length.GetHashCode();

    /// <inheritdoc cref="global::SharpMeasures.Scalar.CompareTo(global::SharpMeasures.Scalar)"/>
    public int CompareTo(global::UnitOfLength? other) => Length.Magnitude.Value.CompareTo(other?.Length.Magnitude.Value);

    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &lt;(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator <(global::UnitOfLength? x, global::UnitOfLength? y) => x?.Length.Magnitude.Value < y?.Length.Magnitude.Value;
    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &gt;(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator >(global::UnitOfLength? x, global::UnitOfLength? y) => x?.Length.Magnitude.Value > y?.Length.Magnitude.Value;
    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &lt;=(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator <=(global::UnitOfLength? x, global::UnitOfLength? y) => x?.Length.Magnitude.Value <= y?.Length.Magnitude.Value;
    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &gt;=(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator >=(global::UnitOfLength? x, global::UnitOfLength? y) => x?.Length.Magnitude.Value >= y?.Length.Magnitude.Value;
}
