namespace SharpMeasures.Generators.Units.Pipelines.UnitDefinitions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.Attributes.Parsing.Units;
using SharpMeasures.Generators.Diagnostics;
using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, DataModel result)
    {
        if (result.DerivedUnits.Any() is false && result.FixedUnits.Any() is false && result.UnitAliases.Any() is false && result.OffsetUnits.Any() is false
            && result.PrefixedUnits.Any() is false && result.ScaledUnits.Any() is false)
        {
            return;
        }

        string source = Composer.Compose(context, result);

        context.AddSource($"{result.Unit.Name}_Definitions.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private class Composer
    {
        public static string Compose(SourceProductionContext context, DataModel data)
        {
            Composer composer = new(context, data);
            composer.Compose();
            composer.ReportDiagnostics();
            return composer.Retrieve();
        }

        private SourceProductionContext Context { get; }
        private StringBuilder Builder { get; } = new();
        private UsingsCollector UsingsCollector { get; }

        private DataModel Data { get; }

        private HashSet<string> ImplementedDefinitions { get; } = new();

        private List<Diagnostic> Diagnostics { get; } = new();

        private Composer(SourceProductionContext context, DataModel data)
        {
            Context = context;
            Data = data;
            UsingsCollector = UsingsCollector.Delayed(Builder, data.Unit.Namespace);

            UsingsCollector.AddUsing("SharpMeasures");
            UsingsCollector.AddUsing(Data.Quantity.Namespace);
        }

        private void Compose()
        {
            StaticBuilding.AppendAutoGeneratedHeader(Builder);
            StaticBuilding.AppendNullableDirective(Builder);

            NamespaceBuilding.AppendNamespace(Builder, Data.Unit.Namespace);

            UsingsCollector.MarkInsertionPoint();

            Builder.Append(Data.Unit.ComposeDeclaration());

            BlockBuilding.AppendBlock(Builder, ComposeTypeBlock, originalIndentationLevel: 0);

            UsingsCollector.InsertUsings();
        }

        private void ReportDiagnostics()
        {
            Context.ReportDiagnostics(Diagnostics);
        }

        private string Retrieve()
        {
            return Builder.ToString();
        }

        private void ComposeTypeBlock(Indentation indentation)
        {
            AppendDerived(indentation);
            AppendFixed(indentation);

            AppendDependantUnits(indentation);
        }

        private void AppendDerived(Indentation indentation)
        {
            foreach (DerivedUnit derivedUnit in Data.DerivedUnits)
            {
                ImplementedDefinitions.Add(derivedUnit.Name);

                AppendDocumentation(indentation, derivedUnit);
                Builder.Append($"{indentation}public static {Data.Unit.Name} {derivedUnit.Name} {{ get; }} = ");

                IterativeBuilding.AppendEnumerable(Builder, "From(", arguments(), ", ", $");{Environment.NewLine}");

                IEnumerable<string> arguments()
                {
                    IEnumerator<NamedType> signatureIterator = derivedUnit.Signature.Types.GetEnumerator();
                    IEnumerator<string> unitIterator = derivedUnit.Units.GetEnumerator();

                    while (signatureIterator.MoveNext() && unitIterator.MoveNext())
                    {
                        UsingsCollector.AddUsing(signatureIterator.Current.Namespace);
                        yield return $"{signatureIterator.Current.Name}.{unitIterator.Current}";
                    }
                }
            }
        }

        private void AppendFixed(Indentation indentation)
        {
            Action<FixedUnit> appender = Data.Biased ? appendBiased : appendUnbiased;

            foreach (FixedUnit fixedUnit in Data.FixedUnits)
            {
                ImplementedDefinitions.Add(fixedUnit.Name);

                appender(fixedUnit);
            }

            void appendDeclaration(FixedUnit fixedUnit)
            {
                AppendDocumentation(indentation, fixedUnit);
                Builder.Append($"{indentation}public static {Data.Unit.Name} {fixedUnit.Name} {{ get; }}");
            }

            void appendUnbiased(FixedUnit fixedUnit)
            {
                appendDeclaration(fixedUnit);
                Builder.AppendLine($" = new(new {Data.Quantity.Name}({fixedUnit.Value}));");
            }

            void appendBiased(FixedUnit fixedUnit)
            {
                appendDeclaration(fixedUnit);
                Builder.AppendLine($" = new(new {Data.Quantity.Name}({fixedUnit.Value}), new Scalar({fixedUnit.Bias}));");
            }
        }

        private void AppendDependantUnits(Indentation indentation) => AppendDependantUnits(indentation, GetDependantInstances());

        private void AppendDependantUnits(Indentation indentation, IList<IDependantUnitDefinition> dependantUnits)
        {
            int initialLength = dependantUnits.Count;

            for (int i = 0; i < dependantUnits.Count; i++)
            {
                if (ImplementedDefinitions.Contains(dependantUnits[i].DependantOn))
                {
                    AppendDocumentation(indentation, dependantUnits[i]);
                    Builder.Append($"{indentation}public static {Data.Unit.Name} {dependantUnits[i].Name} ");

                    if (dependantUnits[i] is UnitAlias unitAlias)
                    {
                        AppendAlias(unitAlias);
                    }
                    else if (dependantUnits[i] is ScaledUnit scaledUnit)
                    {
                        AppendScaled(scaledUnit);
                    }
                    else if (dependantUnits[i] is PrefixedUnit prefixedUnit)
                    {
                        AppendPrefixed(prefixedUnit);
                    }
                    else if (dependantUnits[i] is OffsetUnit offsetUnit)
                    {
                        AppendOffset(offsetUnit);
                    }

                    Builder.AppendLine($";");

                    ImplementedDefinitions.Add(dependantUnits[i].Name);
                    dependantUnits.RemoveAt(i);
                    i--;
                }
            }

            if (dependantUnits.Count is 0)
            {
                return;
            }
            
            if (dependantUnits.Count < initialLength)
            {
                AppendDependantUnits(indentation, dependantUnits);
                return;
            }

            CreateCyclicDependencyDiagnostics(dependantUnits);
        }

        private void AppendAlias(UnitAlias unitAlias)
        {
            Builder.Append($"=> {unitAlias.AliasOf}");
        }

        private void AppendScaled(ScaledUnit scaledUnit)
        {
            Builder.Append($"{{ get; }} = {scaledUnit.From}.ScaledBy({scaledUnit.Scale})");
        }

        private void AppendPrefixed(PrefixedUnit prefixedUnit)
        {
            string prefixText = prefixedUnit.Locations.ExplicitlySetMetricPrefixName
                ? $"MetricPrefix.{prefixedUnit.MetricPrefixName}"
                : $"BinaryPrefix.{prefixedUnit.BinaryPrefixName}";

            Builder.Append($"{{ get; }} = {prefixedUnit.From}.WithPrefix({prefixText})");
        }

        private void AppendOffset(OffsetUnit offsetUnit)
        {
            Builder.Append($"{{ get; }} = {offsetUnit.From}.ScaledBy({offsetUnit.Offset})");
        }

        private List<IDependantUnitDefinition> GetDependantInstances()
        {
            List<IDependantUnitDefinition> result = new();

            foreach (UnitAlias unitAlias in Data.UnitAliases)
            {
                result.Add(unitAlias);
            }

            foreach (OffsetUnit offsetUnit in Data.OffsetUnits)
            {
                result.Add(offsetUnit);
            }

            foreach (PrefixedUnit prefixedUnit in Data.PrefixedUnits)
            {
                result.Add(prefixedUnit);
            }

            foreach (ScaledUnit scaledUnit in Data.ScaledUnits)
            {
                result.Add(scaledUnit);
            }

            return result;
        }

        private void AppendDocumentation(Indentation indentation, IUnitDefinition definition)
        {
            DocumentationBuilding.AppendDocumentation(Context, Builder, Data.Documentation, indentation, UnitDocumentationTags.Definition.WithName(definition.Name));
        }

        private void CreateCyclicDependencyDiagnostics(IList<IDependantUnitDefinition> dependantUnits)
        {
            foreach (var dependantUnit in dependantUnits)
            {
                Diagnostic diagnostics = DiagnosticConstruction.CyclicDependency(dependantUnit.Locations.Attribute.AsRoslynLocation(),
                    dependantUnit.Name, Data.Unit.Name);

                Diagnostics.Add(diagnostics);
            }
        }
    }
}
