namespace SharpMeasures.Generators.Units.Pipeline.UnitDefinitions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.Attributes.Parsing.Units;
using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Collections.Generic;
using System.Text;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, DataModel result)
    {
        if (result.DerivedUnits.Count is 0 && result.FixedUnits.Count is 0 && result.UnitAliases.Count is 0 && result.OffsetUnits.Count is 0
            && result.PrefixedUnits.Count is 0 && result.ScaledUnits.Count is 0)
        {
            return;
        }

        string source = Composer.Compose(context, result);

        context.AddSource($"{result.Unit.Name}_Definitions.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private class Composer
    {
        public static string Compose(SourceProductionContext context, DataModel data)
        {
            Composer composer = new(context, data);
            composer.Compose();
            return composer.Retrieve();
        }

        private SourceProductionContext Context { get; }
        private StringBuilder Builder { get; } = new();
        private UsingsCollector UsingsCollector { get; }

        private DataModel Data { get; }

        private HashSet<string> ImplementedDefinitions { get; } = new();

        private Composer(SourceProductionContext context, DataModel data)
        {
            Context = context;
            Data = data;
            UsingsCollector = UsingsCollector.Delayed(Builder, data.Unit.Namespace);

            UsingsCollector.AddUsing("SharpMeasures");
            UsingsCollector.AddUsing(Data.Quantity.Namespace);
        }

        private void Compose()
        {
            StaticBuilding.AppendAutoGeneratedHeader(Builder);
            StaticBuilding.AppendNullableDirective(Builder);

            NamespaceBuilding.AppendNamespace(Builder, Data.Unit.Namespace);

            UsingsCollector.MarkInsertionPoint();

            Builder.Append(Data.Unit.ComposeDeclaration());

            BlockBuilding.AppendBlock(Builder, ComposeTypeBlock, originalIndentationLevel: 0);

            UsingsCollector.InsertUsings();
        }

        private string Retrieve()
        {
            return Builder.ToString();
        }

        private void ComposeTypeBlock(Indentation indentation)
        {
            AppendDerived(indentation);
            AppendFixed(indentation);

            AppendDependantUnits(indentation);
        }

        private void AppendDerived(Indentation indentation)
        {
            foreach (CacheableDerivedUnitDefinition derivedUnit in Data.DerivedUnits)
            {
                ImplementedDefinitions.Add(derivedUnit.Name);

                AppendDocumentation(indentation, derivedUnit);
                Builder.Append($"{indentation}public static {Data.Unit.Name} {derivedUnit.Name} {{ get; }} = ");

                IterativeBuilding.AppendEnumerable(Builder, "From(", arguments(), ", ", $");{Environment.NewLine}");

                IEnumerable<string> arguments()
                {
                    IEnumerator<NamedType> signatureIterator = derivedUnit.Signature.GetEnumerator();
                    IEnumerator<string> unitIterator = derivedUnit.Units.GetEnumerator();

                    while (signatureIterator.MoveNext() && unitIterator.MoveNext())
                    {
                        UsingsCollector.AddUsing(signatureIterator.Current.Namespace);
                        yield return $"{signatureIterator.Current.Name}.{unitIterator.Current}";
                    }
                }
            }
        }

        private void AppendFixed(Indentation indentation)
        {
            Action<CacheableFixedUnitDefinition> appender = Data.Biased ? appendBiased : appendUnbiased;

            foreach (CacheableFixedUnitDefinition fixedUnit in Data.FixedUnits)
            {
                ImplementedDefinitions.Add(fixedUnit.Name);

                appender(fixedUnit);
            }

            void appendDeclaration(CacheableFixedUnitDefinition fixedUnit)
            {
                AppendDocumentation(indentation, fixedUnit);
                Builder.Append($"{indentation}public static {Data.Unit.Name} {fixedUnit.Name} {{ get; }}");
            }

            void appendUnbiased(CacheableFixedUnitDefinition fixedUnit)
            {
                appendDeclaration(fixedUnit);
                Builder.Append($" = new(new {Data.Quantity.Name}({fixedUnit.Value}));{Environment.NewLine}");
            }

            void appendBiased(CacheableFixedUnitDefinition fixedUnit)
            {
                appendDeclaration(fixedUnit);
                Builder.Append($" = new(new {Data.Quantity.Name}({fixedUnit.Value}), new Scalar({fixedUnit.Bias}));{Environment.NewLine}");
            }
        }

        private void AppendDependantUnits(Indentation indentation) => AppendDependantUnits(indentation, GetDependantInstances());

        private void AppendDependantUnits(Indentation indentation, IList<ICacheableDependantUnitDefinition> dependantUnits)
        {
            int initialLength = dependantUnits.Count;

            for (int i = 0; i < dependantUnits.Count; i++)
            {
                if (ImplementedDefinitions.Contains(dependantUnits[i].DependantOn))
                {
                    AppendDocumentation(indentation, dependantUnits[i]);
                    Builder.Append($"{indentation}public static {Data.Unit.Name} {dependantUnits[i].Name} ");

                    if (dependantUnits[i] is CacheableUnitAliasDefinition unitAlias)
                    {
                        AppendAlias(unitAlias);
                    }
                    else if (dependantUnits[i] is CacheableScaledUnitDefinition scaledUnit)
                    {
                        AppendScaled(scaledUnit);
                    }
                    else if (dependantUnits[i] is CacheablePrefixedUnitDefinition prefixedUnit)
                    {
                        AppendPrefixed(prefixedUnit);
                    }
                    else if (dependantUnits[i] is CacheableOffsetUnitDefinition offsetUnit)
                    {
                        AppendOffset(offsetUnit);
                    }

                    Builder.Append($";{Environment.NewLine}");

                    ImplementedDefinitions.Add(dependantUnits[i].Name);
                    dependantUnits.RemoveAt(i);
                    i--;
                }
            }

            if (dependantUnits.Count is 0)
            {
                return;
            }
            
            if (dependantUnits.Count < initialLength)
            {
                AppendDependantUnits(indentation, dependantUnits);
            }
        }

        private void AppendAlias(CacheableUnitAliasDefinition unitAlias)
        {
            Builder.Append($"=> {unitAlias.AliasOf}");
        }

        private void AppendScaled(CacheableScaledUnitDefinition scaledUnit)
        {
            Builder.Append($"{{ get; }} = {scaledUnit.From}.ScaledBy({scaledUnit.Scale})");
        }

        private void AppendPrefixed(CacheablePrefixedUnitDefinition prefixedUnit)
        {
            Builder.Append($"{{ get; }} = {prefixedUnit.From}.WithPrefix({prefixText()})");

            string prefixText() => prefixedUnit.ParsingData.SpecifiedPrefixType switch
            {
                PrefixedUnitParsingData.PrefixType.Metric => metricText(),
                PrefixedUnitParsingData.PrefixType.Binary => binaryText(),
                _ => string.Empty
            };

            string metricText() => $"MetricPrefix.{prefixedUnit.MetricPrefixName}";
            string binaryText() => $"BinaryPrefix.{prefixedUnit.BinaryPrefixName}";
        }

        private void AppendOffset(CacheableOffsetUnitDefinition offsetUnit)
        {
            Builder.Append($"{{ get; }} = {offsetUnit.From}.ScaledBy({offsetUnit.Offset})");
        }

        private List<ICacheableDependantUnitDefinition> GetDependantInstances()
        {
            List<ICacheableDependantUnitDefinition> result = new();

            foreach (CacheableUnitAliasDefinition unitAlias in Data.UnitAliases)
            {
                result.Add(unitAlias);
            }

            foreach (CacheableOffsetUnitDefinition offsetUnit in Data.OffsetUnits)
            {
                result.Add(offsetUnit);
            }

            foreach (CacheablePrefixedUnitDefinition prefixedUnit in Data.PrefixedUnits)
            {
                result.Add(prefixedUnit);
            }

            foreach (CacheableScaledUnitDefinition scaledUnit in Data.ScaledUnits)
            {
                result.Add(scaledUnit);
            }

            return result;
        }

        private void AppendDocumentation(Indentation indentation, ICacheableUnitDefinition definition)
        {
            DocumentationBuilding.AppendDocumentation(Context, Builder, Data.Documentation, indentation, DocumentationTags.Definition.WithName(definition.Name));
        }
    }
}
