namespace SharpMeasures.Generators.Units.Pipeline.DerivableUnitPipeline;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.Attributes.Parsing.Units;
using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, DataModel data)
    {
        if (data.DefinedDerivations.Count is 0)
        {
            return;
        }

        string source = Composer.ComposeAndReportDiagnostics(context, data);

        context.AddSource($"{data.Unit.Name}_Derivable.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private class Composer
    {
        public static string ComposeAndReportDiagnostics(SourceProductionContext context, DataModel data)
        {
            Composer composer = new(context, data);
            composer.Compose();
            return composer.Retrieve();
        }

        private SourceProductionContext Context { get; }
        private StringBuilder Builder { get; } = new();

        private DataModel Data { get; }

        private Composer(SourceProductionContext context, DataModel data)
        {
            Context = context;
            Data = data;
        }

        private void Compose()
        {
            StaticBuilding.AppendAutoGeneratedHeader(Builder);
            StaticBuilding.AppendNullableDirective(Builder);

            NamespaceBuilding.AppendNamespace(Builder, Data.Unit);

            Builder.Append(Data.Unit.ComposeDeclaration());

            BlockBuilding.AppendBlock(Builder, ComposeTypeBlock, originalIndentationLevel: 0);
        }

        private string Retrieve()
        {
            return Builder.ToString();
        }

        private void ComposeTypeBlock(StringBuilder source, Indentation indentation)
        {
            foreach (DerivableUnitDefinition definition in Data.DefinedDerivations)
            {
                ComposeDefinition(definition, indentation);
            }
        }

        private void ComposeDefinition(DerivableUnitDefinition definition, Indentation indentation)
        {
            IEnumerable<string> parameterNames = GetSignatureParameterNames(definition.Signature);
            IEnumerable<string> signatureComponents = GetSignatureComponents(definition.Signature, parameterNames);

            string documentationTag = GetUniqueTagForSignature(signatureComponents);

            DocumentationBuilding.AppendDocumentation(Context, Builder, Data.Documentation, indentation, $"From_{documentationTag}");
            Builder.Append($"{indentation}public static {Data.Unit.Name} From(");
            IterativeBuilding.AppendEnumerable(Builder, signatureComponents, ", ");
            Builder.Append($") => new({definition.Expression});{Environment.NewLine}");
        }

        private static IEnumerable<string> GetSignatureParameterNames(IEnumerable<INamedTypeSymbol> signature)
        {
            Dictionary<string, int> counts = new();

            foreach (string signatureComponentName in signatureWithoutNamespaces())
            {
                countParameter(signatureComponentName);
            }

            foreach (string signatureComponentName in signatureWithoutNamespaces())
            {
                yield return $"{SourceBuildingUtility.ToParameterName(signatureComponentName)}{getParameterNumber(signatureComponentName)}";
            }

            IEnumerable<string> signatureWithoutNamespaces()
            {
                foreach (INamedTypeSymbol signatureComponent in signature)
                {
                    yield return signatureComponent.Name.Substring(signatureComponent.Name.LastIndexOf('.') + 1);
                }
            }

            void countParameter(string signatureComponentName)
            {
                if (counts.TryGetValue(signatureComponentName, out int count))
                {
                    counts[signatureComponentName] = count - 1;
                }
                else
                {
                    counts[signatureComponentName] = -1;
                }
            }

            string getParameterNumber(string signatureComponentName)
            {
                int count = counts[signatureComponentName];

                if (count == -1)
                {
                    return string.Empty;
                }
                else if (count < 0)
                {
                    counts[signatureComponentName] = 1;
                    return "1";
                }
                else
                {
                    counts[signatureComponentName] += 1;
                    return counts[signatureComponentName].ToString(CultureInfo.InvariantCulture);
                }
            }
        }

        private static IEnumerable<string> GetSignatureComponents(IEnumerable<INamedTypeSymbol> signature, IEnumerable<string> parameterNames)
        {
            IEnumerator<INamedTypeSymbol> signatureIterator = signature.GetEnumerator();
            IEnumerator<string> parameterIterator = parameterNames.GetEnumerator();

            while (parameterIterator.MoveNext() && signatureIterator.MoveNext())
            {
                yield return $"{signatureIterator.Current.Name} {parameterIterator.Current}";
            }
        }

        private static string GetUniqueTagForSignature(IEnumerable<string> signature)
        {
            StringBuilder tag = new();

            IterativeBuilding.AppendEnumerable(tag, signature, "_");

            return tag.ToString();
        }

        private static string ParseExpression(DerivableUnitDefinition definition, IEnumerable<string> parameterNames)
        {
            string[] symbols = expressionComponents();

            return string.Format(CultureInfo.InvariantCulture, definition.Expression, symbols);

            string[] expressionComponents()
            {
                string[] symbols = new string[definition.Signature.Count];

                IEnumerator<string?> quantityIterator = quantitiesWithoutNamespaces().GetEnumerator();
                IEnumerator<string> parameterIterator = parameterNames.GetEnumerator();

                int index = 0;
                while (quantityIterator.MoveNext() && parameterIterator.MoveNext())
                {
                    symbols[index] = $"{parameterIterator.Current}.{quantityIterator.Current}";
                }

                return symbols;
            }

            IEnumerable<string> quantitiesWithoutNamespaces()
            {
                foreach (INamedTypeSymbol signatureComponentQuantity in definition.Quantities)
                {
                    yield return signatureComponentQuantity.Name.Substring(signatureComponentQuantity.Name.LastIndexOf('.') + 1);
                }
            }
        }
    }
}
