//HintName: Time.Operations.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Scalars <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class Time
{
    /// <summary>Computes { <paramref name="displacement"/> / <see langword="this"/> }.</summary>
    /// <param name="displacement">The dividend of { <paramref name="displacement"/> / <see langword="this"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public global::Velocity2 DivideInto(global::Displacement2 displacement)
    {
        global::System.ArgumentNullException.ThrowIfNull(displacement);

        return new(displacement.Components / Magnitude);
    }

    /// <summary>Computes { <paramref name="displacement"/> / <see langword="this"/> }.</summary>
    /// <param name="displacement">The dividend of { <paramref name="displacement"/> / <see langword="this"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public global::Velocity3 DivideInto(global::Displacement3 displacement)
    {
        global::System.ArgumentNullException.ThrowIfNull(displacement);

        return new(displacement.Components / Magnitude);
    }

    /// <summary>Computes { <see langword="a"/> / <paramref name="b"/> }.</summary>
    /// <param name="a">The dividend of { <see langword="a"/> / <paramref name="b"/> }.</param>
    /// <param name="b">The divisor of { <see langword="a"/> / <paramref name="b"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public static global::Velocity2 operator /(global::Displacement2 a, global::Time b)
    {
        global::System.ArgumentNullException.ThrowIfNull(a);
        global::System.ArgumentNullException.ThrowIfNull(b);

        return new(a.Components / b.Magnitude);
    }

    /// <summary>Computes { <see langword="a"/> / <paramref name="b"/> }.</summary>
    /// <param name="a">The dividend of { <see langword="a"/> / <paramref name="b"/> }.</param>
    /// <param name="b">The divisor of { <see langword="a"/> / <paramref name="b"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public static global::Velocity3 operator /(global::Displacement3 a, global::Time b)
    {
        global::System.ArgumentNullException.ThrowIfNull(a);
        global::System.ArgumentNullException.ThrowIfNull(b);

        return new(a.Components / b.Magnitude);
    }
}
