//HintName: Length.Processes.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Scalars <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class Length
{
    /// <summary>Processes the <see cref="global::Length"/>.</summary>
    public global::Length Name => new(Magnitude);
}
