//HintName: Position3.Operations.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Vectors <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class Position3
{
    /// <summary>Computes { <see langword="this"/> ∙ <paramref name="length"/> }.</summary>
    /// <param name="length">The second factor of { <see langword="this"/> ∙ <paramref name="length"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public global::Position3 Multiply(global::Length length)
    {
        global::System.ArgumentNullException.ThrowIfNull(length);

        return new(Components * length.Magnitude);
    }

    /// <summary>Computes { <see langword="a"/> * <paramref name="b"/> }.</summary>
    /// <param name="a">The first factor of { <see langword="a"/> * <paramref name="b"/> }.</param>
    /// <param name="b">The second factor of { <see langword="a"/> * <paramref name="b"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public static global::Position3 operator *(global::Position3 a, global::Length b)
    {
        global::System.ArgumentNullException.ThrowIfNull(a);
        global::System.ArgumentNullException.ThrowIfNull(b);

        return new(a.Components * b.Magnitude);
    }
}
