//HintName: UnitOfSpeed_Derivable.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Units <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class UnitOfSpeed
{
    /// <summary>Constructs a new <see cref="global::UnitOfSpeed"/>, derived from other units.</summary>
    /// <param name="unitOfLength">This <see cref="global::UnitOfLength"/> is used to derive a <see cref="global::UnitOfSpeed"/>.</param>
    /// <param name="unitOfTime">This <see cref="global::UnitOfTime"/> is used to derive a <see cref="global::UnitOfSpeed"/>.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public static global::UnitOfSpeed From(global::UnitOfLength unitOfLength, global::UnitOfTime unitOfTime)
    {
        global::System.ArgumentNullException.ThrowIfNull(unitOfLength);
        global::System.ArgumentNullException.ThrowIfNull(unitOfTime);

        return new(new global::Speed(unitOfLength.Length.Magnitude / unitOfTime.Time.Magnitude));
    }
}
