namespace SharpMeasures.SourceGenerators.Scalars;

using SharpMeasures.SourceGenerators.Scalars.Pipeline;
using SharpMeasures.SourceGenerators.Utility;

using System.Text;
using System.Threading;

internal static class SourceBuilder
{
    public static string Build(FourthStage.Result data, CancellationToken _)
    {
        StringBuilder source = new();

        SourceBuildingUtility.AppendAutoGeneratedHeader(source);
        SourceBuildingUtility.AppendNullableDirective(source);
        SourceBuildingUtility.AppendNamespace(source, data.TypeSymbol);
        SourceBuildingUtility.AppendTypeDefinition(source, data.TypeSymbol);

        source.Append(
$@"
{{
    /// <summary>The magnitude of the <see cref=""{data.TypeSymbol.Name}""/>, in SI units.</summary>
    public double {data.Parameters.MagnitudePropertyName} {{ get; init; }}
}}"
        );

        return source.ToString();
    }
}
