namespace SharpMeasures.Generators.SourceBuilding;

using System;
using System.Reflection;
using System.Text;

public static class StaticBuilding
{
    public static void AppendAutoGeneratedHeader(StringBuilder source, bool includeVersion = true, bool includeTimestamp = true)
    {
        string versionText = includeVersion ? $" v{Assembly.GetExecutingAssembly().GetName().Version}" : string.Empty;
        string timestampText = includeTimestamp ? $" ({DateTime.UtcNow} UTC)" : string.Empty;

        source.Append($$"""
            //----------------------
            // <auto-generated>
            //      This file was generated by {{Assembly.GetCallingAssembly().GetName().Name}}{{versionText}}{{timestampText}}.
            //
            //      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //----------------------

            """);
    }

    public static void AppendNullableDirective(StringBuilder source)
    {
        source.AppendLine($"#nullable enable");
        source.AppendLine();
    }

    public static void AppendEqualsObjectMethod(StringBuilder source, Indentation indentation, string type)
    {
        source.AppendLine($$"""
            {{indentation}}public override bool Equals(object? obj)
            {{indentation}}{
            {{indentation.Increased}}if (obj is {{type}} other)
            {{indentation.Increased}}{
            {{indentation.Increased.Increased}}return Equals(other);
            {{indentation.Increased}}}

            {{indentation.Increased}}return false;
            {{indentation}}}
            """);
    }
}
