namespace SharpMeasures.Generators.Tests.Scalars;

using Microsoft.CodeAnalysis.Diagnostics;

using SharpMeasures.Generators.DriverUtility;
using SharpMeasures.Generators.Tests.Verify;

using System.Collections.Immutable;
using System.Threading.Tasks;

using VerifyXunit;

using Xunit;

[UsesVerify]
public class AutoGeneratedHeaderContent
{
    [Fact]
    public Task None() => Verify("none");

    [Fact]
    public Task Header() => Verify("header");

    [Fact]
    public Task Tool() => Verify("tool");

    [Fact]
    public Task Version() => Verify("tool, version");

    [Fact]
    public Task ExplicitlyAll() => Verify("header, tool, version, date, time");

    [Fact]
    public Task All() => Verify("all");

    private static Task Verify(string level) => GeneratorVerifier.Construct<SharpMeasuresGenerator>(Text, Configuration(level)).AssertNoDiagnosticsReported().VerifyMatchingSourceNames("Length.Common.g.cs");

    private static string Text => """
        using SharpMeasures.Generators;

        [ScalarQuantity(typeof(UnitOfLength))]
        public partial class Length { }

        [Unit(typeof(Length))]
        public partial class UnitOfLength { }
        """;

    private static DriverConstructionConfiguration Configuration(string level)
    {
        var builder = ImmutableDictionary.CreateBuilder<string, string>();

        builder.Add("SharpMeasures_GeneratedFileHeaderContent", level);

        AnalyzerConfigOptionsProvider provider = new CustomAnalyzerConfigOptionsProvider(new CustomAnalyzerConfigOptions(builder.ToImmutable()));

        return DriverConstructionConfiguration.Empty with { OptionsProvider = provider };
    }
}
