//HintName: Position3.Operations.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Vectors <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class Position3
{
    /// <summary>Computes { <see langword="this"/> ∙ <paramref name="displacement"/> }.</summary>
    /// <param name="displacement">The second factor of { <see langword="this"/> ∙ <paramref name="displacement"/> }.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public global::Length Dot(global::Displacement3 displacement)
    {
        global::System.ArgumentNullException.ThrowIfNull(displacement);

        return new(Components.Dot(displacement.Components));
    }
}
