namespace SharpMeasures.Generators.Vectors.Parsing.Diagnostics.Empty.Validation;

using Microsoft.CodeAnalysis;

using SharpMeasures.Generators.Attributes.Parsing;
using SharpMeasures.Generators.Quantities;
using SharpMeasures.Generators.Quantities.Parsing.DefaultUnitInstance;
using SharpMeasures.Generators.Units;
using SharpMeasures.Generators.Vectors.Parsing.SpecializedSharpMeasuresVectorGroup;

internal sealed class EmptySpecializedSharpMeasuresVectorGroupValidationDiagnostics : ISpecializedSharpMeasuresVectorGroupValidationDiagnostics
{
    public static EmptySpecializedSharpMeasuresVectorGroupValidationDiagnostics Instance { get; } = new();

    private EmptySpecializedSharpMeasuresVectorGroupValidationDiagnostics() { }

    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.TypeAlreadyUnit(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.TypeAlreadyScalar(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.TypeAlreadyVector(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.TypeAlreadyVectorGroupBase(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.OriginalNotVectorGroup(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.RootVectorGroupNotResolved(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.TypeNotScalar(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? ISpecializedSharpMeasuresVectorGroupValidationDiagnostics.DifferenceNotVectorGroup(ISpecializedSharpMeasuresVectorGroupValidationContext context, SpecializedSharpMeasuresVectorGroupDefinition definition) => null;
    Diagnostic? IDefaultUnitInstanceValidationDiagnostics.UnrecognizedDefaultUnitInstance(IProcessingContext context, IDefaultUnitInstanceDefinition definition, IUnitType unit) => null;
}
