//HintName: UnitOfTemperature_Instances.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Units <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class UnitOfTemperature
{
    /// <summary>A <see cref="global::UnitOfTemperature"/>, describing a certain <see cref="global::TemperatureDifference"/> and an associated <see cref="global::SharpMeasures.Scalar"/> bias term.</summary>
    public static global::UnitOfTemperature Kelvin { get; } = new(new global::TemperatureDifference(1), new global::SharpMeasures.Scalar(0));

    /// <summary>A <see cref="global::UnitOfTemperature"/>, describing a certain <see cref="global::TemperatureDifference"/> and an associated <see cref="global::SharpMeasures.Scalar"/> bias term.</summary>
    public static global::UnitOfTemperature Celsius { get; } = Kelvin.WithBias(-273.15);
}
