namespace SharpMeasures.Generators.Units.Pipeline.ComparablePipeline;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Text;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, Stage4.Result result)
    {
        string source = Compose(context, result);

        context.AddSource($"{result.TypeDefinition.Name}_Comparable.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Compose(SourceProductionContext context, Stage4.Result data)
    {
        StringBuilder source = new();

        string unitName = data.TypeDefinition.Name;
        string quantityName = data.Quantity.Name;

        StaticBuilding.AppendAutoGeneratedHeader(source);
        StaticBuilding.AppendNullableDirective(source);

        NamespaceBuilding.AppendNamespace(source, data.TypeDefinition.Namespace);

        UsingsBuilding.AppendUsings(source, new string[]
        {
            "System"
        });

        source.Append(data.TypeDefinition.ComposeDeclaration());

        InterfaceBuilding.AppendInterfaceImplementation(source, new string[]
        {
            $"IComparable<{unitName}>"
        });

        BlockBuilding.AppendBlock(source, typeBlock, originalIndentationLevel: 0);

        void typeBlock(StringBuilder source, Indentation indentation)
        {
            DocumentationBuilding.AppendDocumentation(context, source, data.Documentation, indentation, "CompareTo_SameType");
            source.Append($@"{indentation}public int CompareTo({unitName} other) => {quantityName}.CompareTo(other.{quantityName});{Environment.NewLine}");

            source.Append(Environment.NewLine);
            DocumentationBuilding.AppendDocumentation(context, source, data.Documentation, indentation, "Operator_LessThan_SameType");
            source.Append($@"{indentation}public static bool operator <(UnitOfLength x, UnitOfLength y) => x.Length < y.Length;{Environment.NewLine}");
            DocumentationBuilding.AppendDocumentation(context, source, data.Documentation, indentation, "Operator_GreaterThan_SameType");
            source.Append($@"{indentation}public static bool operator >(UnitOfLength x, UnitOfLength y) => x.Length > y.Length;{Environment.NewLine}");
            DocumentationBuilding.AppendDocumentation(context, source, data.Documentation, indentation, "Operator_LessThanOrEqual_SameType");
            source.Append($@"{indentation}public static bool operator <=(UnitOfLength x, UnitOfLength y) => x.Length <= y.Length;{Environment.NewLine}");
            DocumentationBuilding.AppendDocumentation(context, source, data.Documentation, indentation, "Operator_GreaterThanOrEqual_SameType");
            source.Append($@"{indentation}public static bool operator >=(UnitOfLength x, UnitOfLength y) => x.Length >= y.Length;");
        }

        return source.ToString();
    }
}
