namespace SharpMeasures.Generators.Units.Pipeline.ComparablePipeline;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SharpMeasures.Generators.SourceBuilding;

using System;
using System.Text;
using System.Threading;

internal static class Execution
{
    public static void Execute(SourceProductionContext context, Stage4.Result result)
    {
        string source = Compose(result, context.CancellationToken);

        context.AddSource($"{result.TypeDefinition.Name.Name}_Comparable.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Compose(Stage4.Result data, CancellationToken _)
    {
        StringBuilder source = new();

        string unitName = data.TypeDefinition.Name.Name;
        string quantityName = data.Quantity.Name;

        StaticBuilding.AppendAutoGeneratedHeader(source);
        StaticBuilding.AppendNullableDirective(source);

        NamespaceBuilding.AppendNamespace(source, data.TypeDefinition.Name.NameSpace);

        UsingsBuilding.AppendUsings(source, new string[]
        {
            "System"
        });

        source.Append(data.TypeDefinition.ComposeDeclaration());

        InterfaceBuilding.AppendInterfaceImplementation(source, new string[]
        {
            $"IComparable<{unitName}>"
        });

        BlockBuilding.AppendBlock(source, typeBlock, originalIndentationLevel: 0);

        void typeBlock(StringBuilder source, Indentation indentation)
        {
            source.Append($"{Environment.NewLine}{indentation}public int CompareTo({unitName} other) => " +
                $"{quantityName}.CompareTo(other.{quantityName});{Environment.NewLine}");

            source.Append($"{Environment.NewLine}{indentation}public static bool operator <({unitName} x, {unitName} y) " +
                $"=> x.{quantityName} < y.{quantityName};");
            source.Append($"{Environment.NewLine}{indentation}public static bool operator >({unitName} x, {unitName} y) " +
                $"=> x.{quantityName} > y.{quantityName};");
            source.Append($"{Environment.NewLine}{indentation}public static bool operator <=({unitName} x, {unitName} y) " +
                $"=> x.{quantityName} <= y.{quantityName};");
            source.Append($"{Environment.NewLine}{indentation}public static bool operator >=({unitName} x, {unitName} y) " +
                $"=> x.{quantityName} >= y.{quantityName};");
        }

        return source.ToString();
    }
}
