//HintName: OverridenSelfType.Common.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Scalars <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

/// <summary>This is a cref="int"/>.</summary>
public partial class OverridenSelfType :
    global::SharpMeasures.IScalarQuantity<global::OverridenSelfType>,
    global::System.IComparable<global::OverridenSelfType>,
    global::System.IEquatable<global::OverridenSelfType>
{
    /// <summary>The <see cref="global::OverridenSelfType"/> representing { 0 }.</summary>
    public static global::OverridenSelfType Zero { get; } = new(0);

    /// <summary>The magnitude of <see langword="this"/>, expressed in an arbitrary unit.</summary>
    /// <remarks>In most cases, expressing the magnitude in a specified <see cref="global::UnitOfDocTest"/> should be preferred. This is achieved through <see cref="InUnit(global::UnitOfDocTest)"/>.</remarks>
    public global::SharpMeasures.Scalar Magnitude { get; }

    /// <summary>Constructs a new <see cref="global::OverridenSelfType"/> representing { <paramref name="magnitude"/> }, expressed in an arbitrary unit.</summary>
    /// <param name="magnitude">The magnitude represented by the constructed <see cref="global::OverridenSelfType"/>, expressed in an arbitrary unit.</param>
    /// <remarks>Consider preferring construction through <see cref="global::OverridenSelfType(global::SharpMeasures.Scalar, global::UnitOfDocTest)"/>, where the magnitude is expressed in
    /// a specified <see cref="global::UnitOfDocTest"/>.</remarks>
    public OverridenSelfType(global::SharpMeasures.Scalar magnitude)
    {
        Magnitude = magnitude;
    }

    /// <summary>Constructs a new <see cref="global::OverridenSelfType"/> representing { <paramref name="magnitude"/> }, when expressed in <paramref name="unitOfDocTest"/>.</summary>
    /// <param name="magnitude">The magnitude represented by the constructed <see cref="global::OverridenSelfType"/>, when expressed in <paramref name="unitOfDocTest"/>.</param>
    /// <param name="unitOfDocTest">The <see cref="global::UnitOfDocTest"/> in which <paramref name="magnitude"/> is expressed.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public OverridenSelfType(global::SharpMeasures.Scalar magnitude, global::UnitOfDocTest unitOfDocTest)
        : this(ComputeRepresentedMagnitude(magnitude, unitOfDocTest)) { }

    /// <summary>The magnitude of <see langword="this"/>, expressed in <paramref name="unitOfDocTest"/>.</summary>
    /// <param name="unitOfDocTest">The <see cref="global::UnitOfDocTest"/> in which the magnitude of <see langword="this"/> is expressed.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    public global::SharpMeasures.Scalar InUnit(global::UnitOfDocTest unitOfDocTest)
    {
        global::System.ArgumentNullException.ThrowIfNull(unitOfDocTest);

        return new(Magnitude / unitOfDocTest.OverridenSelfType.Magnitude);
    }

    /// <summary>Produces a description of <see langword="this"/> containing the represented <see cref="Magnitude"/>, expressed in an arbitrary unit.</summary>
    public override string ToString() => Magnitude.ToString();

    /// <inheritdoc/>
    public virtual bool Equals(global::OverridenSelfType? other) => other is not null && Magnitude.Value == other.Magnitude.Value;

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is global::OverridenSelfType other && Equals(other);

    /// <summary>Indicates whether <paramref name="lhs"/> and <paramref name="rhs"/> represent equivalent magnitudes.</summary>
    /// <param name="lhs">The left-hand side of the equality check.</param>
    /// <param name="rhs">The right-hand side of the equality check.</param>
    public static bool operator ==(global::OverridenSelfType? lhs, global::OverridenSelfType? rhs) => lhs?.Equals(rhs) ?? rhs is null;

    /// <summary>Indicates whether <paramref name="lhs"/> and <paramref name="rhs"/> represent inequivalent magnitudes.</summary>
    /// <param name="lhs">The left-hand side of the inequality check.</param>
    /// <param name="rhs">The right-hand side of the inequality check.</param>
    public static bool operator !=(global::OverridenSelfType? lhs, global::OverridenSelfType? rhs) => (lhs == rhs) is false;

    /// <inheritdoc/>
    public override int GetHashCode() => Magnitude.GetHashCode();

    /// <inheritdoc cref="global::SharpMeasures.Scalar.CompareTo(global::SharpMeasures.Scalar)"/>
    public int CompareTo(global::OverridenSelfType? other) => Magnitude.Value.CompareTo(other?.Magnitude.Value);

    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &lt;(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator <(global::OverridenSelfType? x, global::OverridenSelfType? y) => x?.Magnitude.Value < y?.Magnitude.Value;
    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &gt;(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator >(global::OverridenSelfType? x, global::OverridenSelfType? y) => x?.Magnitude.Value > y?.Magnitude.Value;
    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &lt;=(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator <=(global::OverridenSelfType? x, global::OverridenSelfType? y) => x?.Magnitude.Value <= y?.Magnitude.Value;
    /// <inheritdoc cref="global::SharpMeasures.Scalar.operator &gt;=(global::SharpMeasures.Scalar, global::SharpMeasures.Scalar)"/>
    public static bool operator >=(global::OverridenSelfType? x, global::OverridenSelfType? y) => x?.Magnitude.Value >= y?.Magnitude.Value;

    /// <inheritdoc/>
    static global::OverridenSelfType global::SharpMeasures.IScalarQuantity<global::OverridenSelfType>.WithMagnitude(global::SharpMeasures.Scalar magnitude) => new(magnitude);

    /// <summary>Computes the represented magnitude based on a magnitude, <paramref name="magnitude"/>, expressed in
    /// a certain unit <paramref name="unitOfDocTest"/>.</summary>
    /// <param name="magnitude">The magnitude expressed in a certain unit <paramref name="unitOfDocTest"/>.</param>
    /// <param name="unitOfDocTest">The <see cref="global::UnitOfDocTest"/> in which <paramref name="magnitude"/> is expressed.</param>
    /// <exception cref="global::System.ArgumentNullException"/>
    private static global::SharpMeasures.Scalar ComputeRepresentedMagnitude(global::SharpMeasures.Scalar magnitude, global::UnitOfDocTest unitOfDocTest)
    {
        global::System.ArgumentNullException.ThrowIfNull(unitOfDocTest);

        return magnitude * unitOfDocTest.OverridenSelfType.Magnitude;
    }
}
