//HintName: Distance.Units.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators.Scalars <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class Distance
{
    /// <summary>The <see cref="global::Distance"/> representing { 1.616E-35 <see cref="global::UnitOfLength.Metre"/> }.</summary>
    public static global::Distance Planck => new(1.616255E-35, global::UnitOfLength.Metre);

    /// <summary>The <see cref="global::Distance"/> representing { 1 <see cref="global::UnitOfLength.Metre"/> }.</summary>
    public static global::Distance OneMetre => new(global::UnitOfLength.Metre.Length.Magnitude);

    /// <summary>The magnitude of <see langword="this"/>, expressed in multiples of <see cref="global::Distance.Planck"/>.</summary>
    public global::SharpMeasures.Scalar MultiplesOfPlanck => Magnitude.Value / Planck.Magnitude.Value;

    /// <summary>The magnitude of <see langword="this"/>, expressed in <see cref="global::UnitOfLength.Metre"/>.</summary>
    public global::SharpMeasures.Scalar Metres => InUnit(global::UnitOfLength.Metre);
}
