//HintName: UnitOfTemperature_Misc.g.cs
//----------------------
// <auto-generated>
//      This file was generated by SharpMeasures.Generators <stamp>
//
//      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------

#nullable enable

public partial class UnitOfTemperature
{
	public TemperatureDifference TemperatureDifference { get; }
	public Scalar Offset { get; }

	private UnitOfTemperature(TemperatureDifference temperatureDifference, Scalar offset)
	{
		TemperatureDifference = temperatureDifference;
		Offset = offset;
	}

	public UnitOfTemperature ScaledBy(SharpMeasures.Scalar scale) => ScaledBy(scale.Magnitude);
	public UnitOfTemperature ScaledBy(double scale) => new(TemperatureDifference * scale, Offset / scale);

	public UnitOfTemperature OffsetBy(SharpMeasures.Scalar offset) => OffsetBy(offset.Magnitude);
	public UnitOfTemperature OffsetBy(double offset) => new(TemperatureDifference, Offset + offset);

	public UnitOfTemperature WithPrefix(SharpMeasures.MetricPrefix prefix) => ScaledBy(prefix.Scale);

	public override string ToString() => $"{typeof(UnitOfTemperature)}: ({TemperatureDifference} + {Offset})";
}
